#!/bin/bash
#this script will download the latest TransistorTester-old from github.com
#The copy of the github archiv is  located in your local home directory
# at the subdirectory git (can be changed by git_base variable).
# You should not modify the downloaded files directly to enable
# further updates from github.com.
#
################################################################
# The following setting specity the location of your local     #
# clone copy of the TransistorTester-old-versions archive.     #
# You can specify any subdirectory of your HOME directory ./   #
git_base="git"
################################################################
# The folowing two settings specify the location of the
# github master archive.
git_0_dir="kubi48"
git_o_name="TransistorTester-old-versions"
#
echo "I try to get the ${git_o_name} archiv with git:"
mkdir -p ~/${gitbase}
cd ~/${git_base}
if [ -d ./${git_o_name} ]
then
 cd ./${git_o_name}
 echo "Update the ~/${git_base}/${git_o_name} Archiv"
 git pull
else
 echo "Create the ~/${git_base}/${git_o_name} Archiv"
 git clone https://github.com/${git_o_dir}/${git_o_name}
fi
if [ $? -eq 0 ]
then
 echo "Your '~/${git_base}/${git_o_name}' directory is updated with old TransistorTester versions"
else
 echo " "
 echo "Error, the directory '~/${git_base}/${git_o_name}' is not updated correctly!!"
fi
